package Model;
// Generated 29-10-2021 20:24:25 by Hibernate Tools 4.3.1



/**
 * Detalleventa generated by hbm2java
 */
public class Detalleventa  implements java.io.Serializable {


     private long idDetalleventa;
     private Producto producto;
     private Venta venta;
     private long cantidad;
     private Long precioventa;

    public Detalleventa() {
    }

	
    public Detalleventa(long idDetalleventa, Producto producto, Venta venta, long cantidad) {
        this.idDetalleventa = idDetalleventa;
        this.producto = producto;
        this.venta = venta;
        this.cantidad = cantidad;
    }
    public Detalleventa(long idDetalleventa, Producto producto, Venta venta, long cantidad, Long precioventa) {
       this.idDetalleventa = idDetalleventa;
       this.producto = producto;
       this.venta = venta;
       this.cantidad = cantidad;
       this.precioventa = precioventa;
    }
   
    public long getIdDetalleventa() {
        return this.idDetalleventa;
    }
    
    public void setIdDetalleventa(long idDetalleventa) {
        this.idDetalleventa = idDetalleventa;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public long getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(long cantidad) {
        this.cantidad = cantidad;
    }
    public Long getPrecioventa() {
        return this.precioventa;
    }
    
    public void setPrecioventa(Long precioventa) {
        this.precioventa = precioventa;
    }




}


