package Model;
// Generated 29-10-2021 20:24:25 by Hibernate Tools 4.3.1


import java.sql.Blob;

/**
 * Documentacion generated by hbm2java
 */
public class Documentacion  implements java.io.Serializable {


     private long idDocumentacion;
     private Producto producto;
     private String tipodocumento;
     private String nomdocumento;
     private String documento;

    public Documentacion() {
    }

	
    public Documentacion(long idDocumentacion, Producto producto) {
        this.idDocumentacion = idDocumentacion;
        this.producto = producto;
    }
    public Documentacion(long idDocumentacion, Producto producto, String tipodocumento, String nomdocumento, String documento) {
       this.idDocumentacion = idDocumentacion;
       this.producto = producto;
       this.tipodocumento = tipodocumento;
       this.nomdocumento = nomdocumento;
       this.documento = documento;
    }
   
    public long getIdDocumentacion() {
        return this.idDocumentacion;
    }
    
    public void setIdDocumentacion(long idDocumentacion) {
        this.idDocumentacion = idDocumentacion;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public String getTipodocumento() {
        return this.tipodocumento;
    }
    
    public void setTipodocumento(String tipodocumento) {
        this.tipodocumento = tipodocumento;
    }
    public String getNomdocumento() {
        return this.nomdocumento;
    }
    
    public void setNomdocumento(String nomdocumento) {
        this.nomdocumento = nomdocumento;
    }
<<<<<<< HEAD

    
    @Column(name="DOCUMENTO")
    public String getDocumento() {
=======
    public Blob getDocumento() {
>>>>>>> master
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }




}


