package Model;
// Generated 10-10-2021 15:45:08 by Hibernate Tools 4.3.1


import java.sql.Blob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Documentacion generated by hbm2java
 */
@Entity
@Table(name="DOCUMENTACION"
    ,schema="BDCLETA"
)
public class Documentacion  implements java.io.Serializable {


     private long idDocumentacion;
     private Producto producto;
     private String tipodocumento;
     private String nomdocumento;
     private String documento;

    public Documentacion() {
    }

	
    public Documentacion(long idDocumentacion, Producto producto) {
        this.idDocumentacion = idDocumentacion;
        this.producto = producto;
    }
    public Documentacion(long idDocumentacion, Producto producto, String tipodocumento, String nomdocumento, String documento) {
       this.idDocumentacion = idDocumentacion;
       this.producto = producto;
       this.tipodocumento = tipodocumento;
       this.nomdocumento = nomdocumento;
       this.documento = documento;
    }
   
     @Id 

    
    @Column(name="ID_DOCUMENTACION", unique=true, nullable=false, precision=10, scale=0)
    public long getIdDocumentacion() {
        return this.idDocumentacion;
    }
    
    public void setIdDocumentacion(long idDocumentacion) {
        this.idDocumentacion = idDocumentacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PRODUCTO", nullable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    
    @Column(name="TIPODOCUMENTO", length=20)
    public String getTipodocumento() {
        return this.tipodocumento;
    }
    
    public void setTipodocumento(String tipodocumento) {
        this.tipodocumento = tipodocumento;
    }

    
    @Column(name="NOMDOCUMENTO", length=20)
    public String getNomdocumento() {
        return this.nomdocumento;
    }
    
    public void setNomdocumento(String nomdocumento) {
        this.nomdocumento = nomdocumento;
    }

    
    @Column(name="DOCUMENTO")
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }




}


