package Model;
// Generated 29-10-2021 20:24:25 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Mantencion generated by hbm2java
 */
public class Mantencion  implements java.io.Serializable {


     private long idMantencion;
     private Usuario usuario;
     private Servicio servicio;
     private char retirodomicilio;
     private Date fecSolicitada;
     private String comentarios;
     private String garantia;
     private Date fecingreso;
     private Date fecsalida;
     private String estadosolicitud;
     private Long valortotal;

    public Mantencion() {
    }

	
    public Mantencion(long idMantencion, Usuario usuario, Servicio servicio, char retirodomicilio, Date fecSolicitada, String estadosolicitud) {
        this.idMantencion = idMantencion;
        this.usuario = usuario;
        this.servicio = servicio;
        this.retirodomicilio = retirodomicilio;
        this.fecSolicitada = fecSolicitada;
        this.estadosolicitud = estadosolicitud;
    }
    public Mantencion(long idMantencion, Usuario usuario, Servicio servicio, char retirodomicilio, Date fecSolicitada, String comentarios, String garantia, Date fecingreso, Date fecsalida, String estadosolicitud, Long valortotal) {
       this.idMantencion = idMantencion;
       this.usuario = usuario;
       this.servicio = servicio;
       this.retirodomicilio = retirodomicilio;
       this.fecSolicitada = fecSolicitada;
       this.comentarios = comentarios;
       this.garantia = garantia;
       this.fecingreso = fecingreso;
       this.fecsalida = fecsalida;
       this.estadosolicitud = estadosolicitud;
       this.valortotal = valortotal;
    }
   
    public long getIdMantencion() {
        return this.idMantencion;
    }
    
    public void setIdMantencion(long idMantencion) {
        this.idMantencion = idMantencion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
    public char getRetirodomicilio() {
        return this.retirodomicilio;
    }
    
    public void setRetirodomicilio(char retirodomicilio) {
        this.retirodomicilio = retirodomicilio;
    }
    public Date getFecSolicitada() {
        return this.fecSolicitada;
    }
    
    public void setFecSolicitada(Date fecSolicitada) {
        this.fecSolicitada = fecSolicitada;
    }
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }
    public String getGarantia() {
        return this.garantia;
    }
    
    public void setGarantia(String garantia) {
        this.garantia = garantia;
    }
    public Date getFecingreso() {
        return this.fecingreso;
    }
    
    public void setFecingreso(Date fecingreso) {
        this.fecingreso = fecingreso;
    }
    public Date getFecsalida() {
        return this.fecsalida;
    }
    
    public void setFecsalida(Date fecsalida) {
        this.fecsalida = fecsalida;
    }
    public String getEstadosolicitud() {
        return this.estadosolicitud;
    }
    
    public void setEstadosolicitud(String estadosolicitud) {
        this.estadosolicitud = estadosolicitud;
    }
    public Long getValortotal() {
        return this.valortotal;
    }
    
    public void setValortotal(Long valortotal) {
        this.valortotal = valortotal;
    }

    @Override
    public String toString() {
        return "Mantencion{" + "idMantencion=" + idMantencion + ", usuario=" + usuario + ", servicio=" + servicio + ", retirodomicilio=" + retirodomicilio + ", fecSolicitada=" + fecSolicitada + ", comentarios=" + comentarios + ", garantia=" + garantia + ", fecingreso=" + fecingreso + ", fecsalida=" + fecsalida + ", estadosolicitud=" + estadosolicitud + ", valortotal=" + valortotal + '}';
    }




}


