package Model;
// Generated 10-10-2021 15:45:08 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mantencion generated by hbm2java
 */
@Entity
@Table(name="MANTENCION"
    ,schema="BDCLETA"
)
public class Mantencion  implements java.io.Serializable {


     private long idMantencion;
     private Usuario usuario;
     private Servicio servicio;
     private String observacion;
     private String garantia;
     private Date fecingreso;
     private Date fecsalida;
     private String estado;

    public Mantencion() {
    }

	
    public Mantencion(long idMantencion, Usuario usuario, Servicio servicio, String garantia, String estado) {
        this.idMantencion = idMantencion;
        this.usuario = usuario;
        this.servicio = servicio;
        this.garantia = garantia;
        this.estado = estado;
    }
    public Mantencion(long idMantencion, Usuario usuario, Servicio servicio, String observacion, String garantia, Date fecingreso, Date fecsalida, String estado) {
       this.idMantencion = idMantencion;
       this.usuario = usuario;
       this.servicio = servicio;
       this.observacion = observacion;
       this.garantia = garantia;
       this.fecingreso = fecingreso;
       this.fecsalida = fecsalida;
       this.estado = estado;
    }
   
     @Id 

    
    @Column(name="ID_MANTENCION", unique=true, nullable=false, precision=10, scale=0)
    public long getIdMantencion() {
        return this.idMantencion;
    }
    
    public void setIdMantencion(long idMantencion) {
        this.idMantencion = idMantencion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USUARIO", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_SERVICIO", nullable=false)
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }

    
    @Column(name="OBSERVACION", length=200)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    
    @Column(name="GARANTIA", nullable=false, length=2)
    public String getGarantia() {
        return this.garantia;
    }
    
    public void setGarantia(String garantia) {
        this.garantia = garantia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECINGRESO", length=7)
    public Date getFecingreso() {
        return this.fecingreso;
    }
    
    public void setFecingreso(Date fecingreso) {
        this.fecingreso = fecingreso;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECSALIDA", length=7)
    public Date getFecsalida() {
        return this.fecsalida;
    }
    
    public void setFecsalida(Date fecsalida) {
        this.fecsalida = fecsalida;
    }

    
    @Column(name="ESTADO", nullable=false, length=10)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


