package Model;
// Generated 10-10-2021 15:45:08 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pago generated by hbm2java
 */
@Entity
@Table(name="PAGO"
    ,schema="BDCLETA"
)
public class Pago  implements java.io.Serializable {


     private long idPago;
     private long monto;

    public Pago() {
    }

    public Pago(long idPago, long monto) {
       this.idPago = idPago;
       this.monto = monto;
    }
   
     @Id 

    
    @Column(name="ID_PAGO", unique=true, nullable=false, precision=10, scale=0)
    public long getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(long idPago) {
        this.idPago = idPago;
    }

    
    @Column(name="MONTO", nullable=false, precision=10, scale=0)
    public long getMonto() {
        return this.monto;
    }
    
    public void setMonto(long monto) {
        this.monto = monto;
    }




}


