package Model;
// Generated 29-10-2021 20:24:25 by Hibernate Tools 4.3.1



/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private long idPago;
     private long monto;

    public Pago() {
    }

    public Pago(long idPago, long monto) {
       this.idPago = idPago;
       this.monto = monto;
    }
   
    public long getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(long idPago) {
        this.idPago = idPago;
    }
    public long getMonto() {
        return this.monto;
    }
    
    public void setMonto(long monto) {
        this.monto = monto;
    }




}


