package Model;
// Generated 29-10-2021 20:24:25 by Hibernate Tools 4.3.1


import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private long idProducto;
     private String nombreproducto;
     private String tipoproducto;
     private String descripcion;
     private String fabricpropia;
     private long valproducto;
     private String marca;
     private String modelo;
     private long stock;
<<<<<<< HEAD
     private String imagen;
     private Set<Detalleventa> detalleventas = new HashSet<Detalleventa>(0);
     private Set<Documentacion> documentacions = new HashSet<Documentacion>(0);
=======
     private Blob imagen;
     private Set detalleventas = new HashSet(0);
     private Set documentacions = new HashSet(0);
>>>>>>> master

    public Producto() {
    }

	
    public Producto(long idProducto, String nombreproducto, String tipoproducto, String fabricpropia, long valproducto, long stock) {
        this.idProducto = idProducto;
        this.nombreproducto = nombreproducto;
        this.tipoproducto = tipoproducto;
        this.fabricpropia = fabricpropia;
        this.valproducto = valproducto;
        this.stock = stock;
    }
<<<<<<< HEAD
    public Producto(long idProducto, String nombreproducto, String tipoproducto, String descripcion, String fabricpropia, long valproducto, String marca, String modelo, long stock, String imagen, Set<Detalleventa> detalleventas, Set<Documentacion> documentacions) {
=======
    public Producto(long idProducto, String nombreproducto, String tipoproducto, String descripcion, String fabricpropia, long valproducto, String marca, String modelo, long stock, Blob imagen, Set detalleventas, Set documentacions) {
>>>>>>> master
       this.idProducto = idProducto;
       this.nombreproducto = nombreproducto;
       this.tipoproducto = tipoproducto;
       this.descripcion = descripcion;
       this.fabricpropia = fabricpropia;
       this.valproducto = valproducto;
       this.marca = marca;
       this.modelo = modelo;
       this.stock = stock;
       this.imagen = imagen;
       this.detalleventas = detalleventas;
       this.documentacions = documentacions;
    }
   
    public long getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(long idProducto) {
        this.idProducto = idProducto;
    }
    public String getNombreproducto() {
        return this.nombreproducto;
    }
    
    public void setNombreproducto(String nombreproducto) {
        this.nombreproducto = nombreproducto;
    }
    public String getTipoproducto() {
        return this.tipoproducto;
    }
    
    public void setTipoproducto(String tipoproducto) {
        this.tipoproducto = tipoproducto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getFabricpropia() {
        return this.fabricpropia;
    }
    
    public void setFabricpropia(String fabricpropia) {
        this.fabricpropia = fabricpropia;
    }
    public long getValproducto() {
        return this.valproducto;
    }
    
    public void setValproducto(long valproducto) {
        this.valproducto = valproducto;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public long getStock() {
        return this.stock;
    }
    
    public void setStock(long stock) {
        this.stock = stock;
    }
<<<<<<< HEAD

    
    @Column(name="IMAGEN")
    public String getImagen() {
=======
    public Blob getImagen() {
>>>>>>> master
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public Set getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set detalleventas) {
        this.detalleventas = detalleventas;
    }
    public Set getDocumentacions() {
        return this.documentacions;
    }
    
    public void setDocumentacions(Set documentacions) {
        this.documentacions = documentacions;
    }




}


