package Model;
// Generated 10-10-2021 15:45:08 by Hibernate Tools 4.3.1


import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="PRODUCTO"
    ,schema="BDCLETA"
)
public class Producto  implements java.io.Serializable {


     private long idProducto;
     private String nombreproducto;
     private String tipoproducto;
     private String descripcion;
     private String fabricpropia;
     private long valproducto;
     private String marca;
     private String modelo;
     private long stock;
     private String imagen;
     private Set<Detalleventa> detalleventas = new HashSet<Detalleventa>(0);
     private Set<Documentacion> documentacions = new HashSet<Documentacion>(0);

    public Producto() {
    }

	
    public Producto(long idProducto, String nombreproducto, String tipoproducto, String fabricpropia, long valproducto, long stock) {
        this.idProducto = idProducto;
        this.nombreproducto = nombreproducto;
        this.tipoproducto = tipoproducto;
        this.fabricpropia = fabricpropia;
        this.valproducto = valproducto;
        this.stock = stock;
    }
    public Producto(long idProducto, String nombreproducto, String tipoproducto, String descripcion, String fabricpropia, long valproducto, String marca, String modelo, long stock, String imagen, Set<Detalleventa> detalleventas, Set<Documentacion> documentacions) {
       this.idProducto = idProducto;
       this.nombreproducto = nombreproducto;
       this.tipoproducto = tipoproducto;
       this.descripcion = descripcion;
       this.fabricpropia = fabricpropia;
       this.valproducto = valproducto;
       this.marca = marca;
       this.modelo = modelo;
       this.stock = stock;
       this.imagen = imagen;
       this.detalleventas = detalleventas;
       this.documentacions = documentacions;
    }
   
     @Id 

    
    @Column(name="ID_PRODUCTO", unique=true, nullable=false, precision=10, scale=0)
    public long getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(long idProducto) {
        this.idProducto = idProducto;
    }

    
    @Column(name="NOMBREPRODUCTO", nullable=false, length=100)
    public String getNombreproducto() {
        return this.nombreproducto;
    }
    
    public void setNombreproducto(String nombreproducto) {
        this.nombreproducto = nombreproducto;
    }

    
    @Column(name="TIPOPRODUCTO", nullable=false, length=15)
    public String getTipoproducto() {
        return this.tipoproducto;
    }
    
    public void setTipoproducto(String tipoproducto) {
        this.tipoproducto = tipoproducto;
    }

    
    @Column(name="DESCRIPCION", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="FABRICPROPIA", nullable=false, length=15)
    public String getFabricpropia() {
        return this.fabricpropia;
    }
    
    public void setFabricpropia(String fabricpropia) {
        this.fabricpropia = fabricpropia;
    }

    
    @Column(name="VALPRODUCTO", nullable=false, precision=10, scale=0)
    public long getValproducto() {
        return this.valproducto;
    }
    
    public void setValproducto(long valproducto) {
        this.valproducto = valproducto;
    }

    
    @Column(name="MARCA", length=15)
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }

    
    @Column(name="MODELO", length=15)
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    
    @Column(name="STOCK", nullable=false, precision=10, scale=0)
    public long getStock() {
        return this.stock;
    }
    
    public void setStock(long stock) {
        this.stock = stock;
    }

    
    @Column(name="IMAGEN")
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set<Detalleventa> getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set<Detalleventa> detalleventas) {
        this.detalleventas = detalleventas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set<Documentacion> getDocumentacions() {
        return this.documentacions;
    }
    
    public void setDocumentacions(Set<Documentacion> documentacions) {
        this.documentacions = documentacions;
    }




}


