package Model;
// Generated 10-10-2021 15:45:08 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name="PROVEEDOR"
    ,schema="BDCLETA"
)
public class Proveedor  implements java.io.Serializable {


     private long idProveedor;
     private String rutProveedor;
     private String nomProveedor;
     private String apeProveedor;
     private String direccionProveedor;
     private Integer telefonoProveedor;
     private String emailProveedor;

    public Proveedor() {
    }

	
    public Proveedor(long idProveedor, String rutProveedor, String nomProveedor) {
        this.idProveedor = idProveedor;
        this.rutProveedor = rutProveedor;
        this.nomProveedor = nomProveedor;
    }
    public Proveedor(long idProveedor, String rutProveedor, String nomProveedor, String apeProveedor, String direccionProveedor, Integer telefonoProveedor, String emailProveedor) {
       this.idProveedor = idProveedor;
       this.rutProveedor = rutProveedor;
       this.nomProveedor = nomProveedor;
       this.apeProveedor = apeProveedor;
       this.direccionProveedor = direccionProveedor;
       this.telefonoProveedor = telefonoProveedor;
       this.emailProveedor = emailProveedor;
    }
   
     @Id 

    
    @Column(name="ID_PROVEEDOR", unique=true, nullable=false, precision=10, scale=0)
    public long getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(long idProveedor) {
        this.idProveedor = idProveedor;
    }

    
    @Column(name="RUT_PROVEEDOR", nullable=false, length=10)
    public String getRutProveedor() {
        return this.rutProveedor;
    }
    
    public void setRutProveedor(String rutProveedor) {
        this.rutProveedor = rutProveedor;
    }

    
    @Column(name="NOM_PROVEEDOR", nullable=false, length=20)
    public String getNomProveedor() {
        return this.nomProveedor;
    }
    
    public void setNomProveedor(String nomProveedor) {
        this.nomProveedor = nomProveedor;
    }

    
    @Column(name="APE_PROVEEDOR", length=20)
    public String getApeProveedor() {
        return this.apeProveedor;
    }
    
    public void setApeProveedor(String apeProveedor) {
        this.apeProveedor = apeProveedor;
    }

    
    @Column(name="DIRECCION_PROVEEDOR", length=25)
    public String getDireccionProveedor() {
        return this.direccionProveedor;
    }
    
    public void setDireccionProveedor(String direccionProveedor) {
        this.direccionProveedor = direccionProveedor;
    }

    
    @Column(name="TELEFONO_PROVEEDOR", precision=9, scale=0)
    public Integer getTelefonoProveedor() {
        return this.telefonoProveedor;
    }
    
    public void setTelefonoProveedor(Integer telefonoProveedor) {
        this.telefonoProveedor = telefonoProveedor;
    }

    
    @Column(name="EMAIL_PROVEEDOR", length=20)
    public String getEmailProveedor() {
        return this.emailProveedor;
    }
    
    public void setEmailProveedor(String emailProveedor) {
        this.emailProveedor = emailProveedor;
    }




}


