package Model;
// Generated 29-10-2021 20:24:25 by Hibernate Tools 4.3.1



/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private long idProveedor;
     private String rutProveedor;
     private String nomProveedor;
     private String apeProveedor;
     private String direccionProveedor;
     private Integer telefonoProveedor;
     private String emailProveedor;

    public Proveedor() {
    }

	
    public Proveedor(long idProveedor, String rutProveedor, String nomProveedor) {
        this.idProveedor = idProveedor;
        this.rutProveedor = rutProveedor;
        this.nomProveedor = nomProveedor;
    }
    public Proveedor(long idProveedor, String rutProveedor, String nomProveedor, String apeProveedor, String direccionProveedor, Integer telefonoProveedor, String emailProveedor) {
       this.idProveedor = idProveedor;
       this.rutProveedor = rutProveedor;
       this.nomProveedor = nomProveedor;
       this.apeProveedor = apeProveedor;
       this.direccionProveedor = direccionProveedor;
       this.telefonoProveedor = telefonoProveedor;
       this.emailProveedor = emailProveedor;
    }
   
    public long getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(long idProveedor) {
        this.idProveedor = idProveedor;
    }
    public String getRutProveedor() {
        return this.rutProveedor;
    }
    
    public void setRutProveedor(String rutProveedor) {
        this.rutProveedor = rutProveedor;
    }
    public String getNomProveedor() {
        return this.nomProveedor;
    }
    
    public void setNomProveedor(String nomProveedor) {
        this.nomProveedor = nomProveedor;
    }
    public String getApeProveedor() {
        return this.apeProveedor;
    }
    
    public void setApeProveedor(String apeProveedor) {
        this.apeProveedor = apeProveedor;
    }
    public String getDireccionProveedor() {
        return this.direccionProveedor;
    }
    
    public void setDireccionProveedor(String direccionProveedor) {
        this.direccionProveedor = direccionProveedor;
    }
    public Integer getTelefonoProveedor() {
        return this.telefonoProveedor;
    }
    
    public void setTelefonoProveedor(Integer telefonoProveedor) {
        this.telefonoProveedor = telefonoProveedor;
    }
    public String getEmailProveedor() {
        return this.emailProveedor;
    }
    
    public void setEmailProveedor(String emailProveedor) {
        this.emailProveedor = emailProveedor;
    }




}


