package Model;
// Generated 09-10-2021 16:47:24 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private BigDecimal idRol;
     private String nombre;
     private Set usuarios = new HashSet(0);

    public Rol() {
    }

	
    public Rol(BigDecimal idRol, String nombre) {
        this.idRol = idRol;
        this.nombre = nombre;
    }
    public Rol(BigDecimal idRol, String nombre, Set usuarios) {
       this.idRol = idRol;
       this.nombre = nombre;
       this.usuarios = usuarios;
    }
   
    public BigDecimal getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(BigDecimal idRol) {
        this.idRol = idRol;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


