package Model;
// Generated 29-10-2021 20:24:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private long idServicio;
     private String descripcionServicio;
     private long precioservicio;
     private Set mantencions = new HashSet(0);

    public Servicio() {
    }

	
    public Servicio(long idServicio, String descripcionServicio, long precioservicio) {
        this.idServicio = idServicio;
        this.descripcionServicio = descripcionServicio;
        this.precioservicio = precioservicio;
    }
    public Servicio(long idServicio, String descripcionServicio, long precioservicio, Set mantencions) {
       this.idServicio = idServicio;
       this.descripcionServicio = descripcionServicio;
       this.precioservicio = precioservicio;
       this.mantencions = mantencions;
    }
   
    public long getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(long idServicio) {
        this.idServicio = idServicio;
    }
    public String getDescripcionServicio() {
        return this.descripcionServicio;
    }
    
    public void setDescripcionServicio(String descripcionServicio) {
        this.descripcionServicio = descripcionServicio;
    }
    public long getPrecioservicio() {
        return this.precioservicio;
    }
    
    public void setPrecioservicio(long precioservicio) {
        this.precioservicio = precioservicio;
    }
    public Set getMantencions() {
        return this.mantencions;
    }
    
    public void setMantencions(Set mantencions) {
        this.mantencions = mantencions;
    }




}


