package Model;
// Generated 10-10-2021 15:45:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Servicio generated by hbm2java
 */
@Entity
@Table(name="SERVICIO"
    ,schema="BDCLETA"
)
public class Servicio  implements java.io.Serializable {


     private long idServicio;
     private String descripcionServicio;
     private long precioservicio;
     private Set<Solicitudmantencion> solicitudmantencions = new HashSet<Solicitudmantencion>(0);
     private Set<Mantencion> mantencions = new HashSet<Mantencion>(0);

    public Servicio() {
    }

	
    public Servicio(long idServicio, String descripcionServicio, long precioservicio) {
        this.idServicio = idServicio;
        this.descripcionServicio = descripcionServicio;
        this.precioservicio = precioservicio;
    }
    public Servicio(long idServicio, String descripcionServicio, long precioservicio, Set<Solicitudmantencion> solicitudmantencions, Set<Mantencion> mantencions) {
       this.idServicio = idServicio;
       this.descripcionServicio = descripcionServicio;
       this.precioservicio = precioservicio;
       this.solicitudmantencions = solicitudmantencions;
       this.mantencions = mantencions;
    }
   
     @Id 

    
    @Column(name="ID_SERVICIO", unique=true, nullable=false, precision=10, scale=0)
    public long getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(long idServicio) {
        this.idServicio = idServicio;
    }

    
    @Column(name="DESCRIPCION_SERVICIO", nullable=false, length=200)
    public String getDescripcionServicio() {
        return this.descripcionServicio;
    }
    
    public void setDescripcionServicio(String descripcionServicio) {
        this.descripcionServicio = descripcionServicio;
    }

    
    @Column(name="PRECIOSERVICIO", nullable=false, precision=10, scale=0)
    public long getPrecioservicio() {
        return this.precioservicio;
    }
    
    public void setPrecioservicio(long precioservicio) {
        this.precioservicio = precioservicio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="servicio")
    public Set<Solicitudmantencion> getSolicitudmantencions() {
        return this.solicitudmantencions;
    }
    
    public void setSolicitudmantencions(Set<Solicitudmantencion> solicitudmantencions) {
        this.solicitudmantencions = solicitudmantencions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="servicio")
    public Set<Mantencion> getMantencions() {
        return this.mantencions;
    }
    
    public void setMantencions(Set<Mantencion> mantencions) {
        this.mantencions = mantencions;
    }




}


