package Model;
// Generated 10-10-2021 15:45:08 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Solicitudmantencion generated by hbm2java
 */
@Entity
@Table(name="SOLICITUDMANTENCION"
    ,schema="BDCLETA"
)
public class Solicitudmantencion  implements java.io.Serializable {


     private long idSolMantencion;
     private Usuario usuario;
     private Servicio servicio;
     private char retirodomicilio;
     private Date fecSolicitada;
     private String descripcion;
     private String estadosolicitud;

    public Solicitudmantencion() {
    }

	
    public Solicitudmantencion(long idSolMantencion, Usuario usuario, Servicio servicio, char retirodomicilio, Date fecSolicitada) {
        this.idSolMantencion = idSolMantencion;
        this.usuario = usuario;
        this.servicio = servicio;
        this.retirodomicilio = retirodomicilio;
        this.fecSolicitada = fecSolicitada;
    }
    public Solicitudmantencion(long idSolMantencion, Usuario usuario, Servicio servicio, char retirodomicilio, Date fecSolicitada, String descripcion, String estadosolicitud) {
       this.idSolMantencion = idSolMantencion;
       this.usuario = usuario;
       this.servicio = servicio;
       this.retirodomicilio = retirodomicilio;
       this.fecSolicitada = fecSolicitada;
       this.descripcion = descripcion;
       this.estadosolicitud = estadosolicitud;
    }
   
     @Id 

    
    @Column(name="ID_SOL_MANTENCION", unique=true, nullable=false, precision=10, scale=0)
    public long getIdSolMantencion() {
        return this.idSolMantencion;
    }
    
    public void setIdSolMantencion(long idSolMantencion) {
        this.idSolMantencion = idSolMantencion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USUARIO", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_SERVICIO", nullable=false)
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }

    
    @Column(name="RETIRODOMICILIO", nullable=false, length=1)
    public char getRetirodomicilio() {
        return this.retirodomicilio;
    }
    
    public void setRetirodomicilio(char retirodomicilio) {
        this.retirodomicilio = retirodomicilio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FEC_SOLICITADA", nullable=false, length=7)
    public Date getFecSolicitada() {
        return this.fecSolicitada;
    }
    
    public void setFecSolicitada(Date fecSolicitada) {
        this.fecSolicitada = fecSolicitada;
    }

    
    @Column(name="DESCRIPCION", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="ESTADOSOLICITUD", length=25)
    public String getEstadosolicitud() {
        return this.estadosolicitud;
    }
    
    public void setEstadosolicitud(String estadosolicitud) {
        this.estadosolicitud = estadosolicitud;
    }




}


