package Model;
// Generated 10-10-2021 15:45:08 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Solicitudarriendo generated by hbm2java
 */
@Entity
@Table(name="SOLICITUDARRIENDO"
    ,schema="BDCLETA"
)
public class Solicitudarriendo  implements java.io.Serializable {


     private long idSolArriendo;
     private Usuario usuario;
     private String tipobicicleta;
     private Date feciniArriendo;
     private Date fecfinArriendo;
     private String formapagoArri;
     private Integer depositogarantia;
     private String comentario;

    public Solicitudarriendo() {
    }

	
    public Solicitudarriendo(long idSolArriendo, Usuario usuario, String tipobicicleta, Date feciniArriendo, Date fecfinArriendo, String formapagoArri) {
        this.idSolArriendo = idSolArriendo;
        this.usuario = usuario;
        this.tipobicicleta = tipobicicleta;
        this.feciniArriendo = feciniArriendo;
        this.fecfinArriendo = fecfinArriendo;
        this.formapagoArri = formapagoArri;
    }
    public Solicitudarriendo(long idSolArriendo, Usuario usuario, String tipobicicleta, Date feciniArriendo, Date fecfinArriendo, String formapagoArri, Integer depositogarantia, String comentario) {
       this.idSolArriendo = idSolArriendo;
       this.usuario = usuario;
       this.tipobicicleta = tipobicicleta;
       this.feciniArriendo = feciniArriendo;
       this.fecfinArriendo = fecfinArriendo;
       this.formapagoArri = formapagoArri;
       this.depositogarantia = depositogarantia;
       this.comentario = comentario;
    }
   
     @Id 

    
    @Column(name="ID_SOL_ARRIENDO", unique=true, nullable=false, precision=10, scale=0)
    public long getIdSolArriendo() {
        return this.idSolArriendo;
    }
    
    public void setIdSolArriendo(long idSolArriendo) {
        this.idSolArriendo = idSolArriendo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USUARIO", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="TIPOBICICLETA", nullable=false, length=20)
    public String getTipobicicleta() {
        return this.tipobicicleta;
    }
    
    public void setTipobicicleta(String tipobicicleta) {
        this.tipobicicleta = tipobicicleta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECINI_ARRIENDO", nullable=false, length=7)
    public Date getFeciniArriendo() {
        return this.feciniArriendo;
    }
    
    public void setFeciniArriendo(Date feciniArriendo) {
        this.feciniArriendo = feciniArriendo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECFIN_ARRIENDO", nullable=false, length=7)
    public Date getFecfinArriendo() {
        return this.fecfinArriendo;
    }
    
    public void setFecfinArriendo(Date fecfinArriendo) {
        this.fecfinArriendo = fecfinArriendo;
    }

    
    @Column(name="FORMAPAGO_ARRI", nullable=false, length=20)
    public String getFormapagoArri() {
        return this.formapagoArri;
    }
    
    public void setFormapagoArri(String formapagoArri) {
        this.formapagoArri = formapagoArri;
    }

    
    @Column(name="DEPOSITOGARANTIA", precision=8, scale=0)
    public Integer getDepositogarantia() {
        return this.depositogarantia;
    }
    
    public void setDepositogarantia(Integer depositogarantia) {
        this.depositogarantia = depositogarantia;
    }

    
    @Column(name="COMENTARIO", length=200)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


