package Model;
// Generated 29-10-2021 20:24:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sucursal generated by hbm2java
 */
public class Sucursal  implements java.io.Serializable {


     private long idSucursal;
     private String nomsucursal;
     private String direccionSucursal;
     private Set reportes = new HashSet(0);

    public Sucursal() {
    }

	
    public Sucursal(long idSucursal, String nomsucursal) {
        this.idSucursal = idSucursal;
        this.nomsucursal = nomsucursal;
    }
    public Sucursal(long idSucursal, String nomsucursal, String direccionSucursal, Set reportes) {
       this.idSucursal = idSucursal;
       this.nomsucursal = nomsucursal;
       this.direccionSucursal = direccionSucursal;
       this.reportes = reportes;
    }
   
    public long getIdSucursal() {
        return this.idSucursal;
    }
    
    public void setIdSucursal(long idSucursal) {
        this.idSucursal = idSucursal;
    }
    public String getNomsucursal() {
        return this.nomsucursal;
    }
    
    public void setNomsucursal(String nomsucursal) {
        this.nomsucursal = nomsucursal;
    }
    public String getDireccionSucursal() {
        return this.direccionSucursal;
    }
    
    public void setDireccionSucursal(String direccionSucursal) {
        this.direccionSucursal = direccionSucursal;
    }
    public Set getReportes() {
        return this.reportes;
    }
    
    public void setReportes(Set reportes) {
        this.reportes = reportes;
    }




}


