package Model;
// Generated 10-10-2021 15:45:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sucursal generated by hbm2java
 */
@Entity
@Table(name="SUCURSAL"
    ,schema="BDCLETA"
)
public class Sucursal  implements java.io.Serializable {


     private long idSucursal;
     private String nomsucursal;
     private String direccionSucursal;
     private Set<Reporte> reportes = new HashSet<Reporte>(0);

    public Sucursal() {
    }

	
    public Sucursal(long idSucursal, String nomsucursal) {
        this.idSucursal = idSucursal;
        this.nomsucursal = nomsucursal;
    }
    public Sucursal(long idSucursal, String nomsucursal, String direccionSucursal, Set<Reporte> reportes) {
       this.idSucursal = idSucursal;
       this.nomsucursal = nomsucursal;
       this.direccionSucursal = direccionSucursal;
       this.reportes = reportes;
    }
   
     @Id 

    
    @Column(name="ID_SUCURSAL", unique=true, nullable=false, precision=10, scale=0)
    public long getIdSucursal() {
        return this.idSucursal;
    }
    
    public void setIdSucursal(long idSucursal) {
        this.idSucursal = idSucursal;
    }

    
    @Column(name="NOMSUCURSAL", nullable=false, length=25)
    public String getNomsucursal() {
        return this.nomsucursal;
    }
    
    public void setNomsucursal(String nomsucursal) {
        this.nomsucursal = nomsucursal;
    }

    
    @Column(name="DIRECCION_SUCURSAL", length=40)
    public String getDireccionSucursal() {
        return this.direccionSucursal;
    }
    
    public void setDireccionSucursal(String direccionSucursal) {
        this.direccionSucursal = direccionSucursal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sucursal")
    public Set<Reporte> getReportes() {
        return this.reportes;
    }
    
    public void setReportes(Set<Reporte> reportes) {
        this.reportes = reportes;
    }




}


