package Model;
// Generated 29-10-2021 20:24:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private long idUsuario;
     private Rol rol;
     private String emailUsuario;
     private String password;
     private String pnombre;
     private String appaterno;
     private String apmaterno;
     private String rutUsuario;
     private Date fechanac;
     private String direccionUsuario;
     private int numtelefono;
     private Set mantencions = new HashSet(0);
     private Set ventas = new HashSet(0);
     private Set solicitudarriendos = new HashSet(0);
     private Set reportes = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(long idUsuario, Rol rol, String password, String pnombre, String appaterno, String rutUsuario, Date fechanac, String direccionUsuario, int numtelefono) {
        this.idUsuario = idUsuario;
        this.rol = rol;
        this.password = password;
        this.pnombre = pnombre;
        this.appaterno = appaterno;
        this.rutUsuario = rutUsuario;
        this.fechanac = fechanac;
        this.direccionUsuario = direccionUsuario;
        this.numtelefono = numtelefono;
    }
    public Usuario(long idUsuario, Rol rol, String emailUsuario, String password, String pnombre, String appaterno, String apmaterno, String rutUsuario, Date fechanac, String direccionUsuario, int numtelefono, Set mantencions, Set ventas, Set solicitudarriendos, Set reportes) {
       this.idUsuario = idUsuario;
       this.rol = rol;
       this.emailUsuario = emailUsuario;
       this.password = password;
       this.pnombre = pnombre;
       this.appaterno = appaterno;
       this.apmaterno = apmaterno;
       this.rutUsuario = rutUsuario;
       this.fechanac = fechanac;
       this.direccionUsuario = direccionUsuario;
       this.numtelefono = numtelefono;
       this.mantencions = mantencions;
       this.ventas = ventas;
       this.solicitudarriendos = solicitudarriendos;
       this.reportes = reportes;
    }
   
    public long getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(long idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getEmailUsuario() {
        return this.emailUsuario;
    }
    
    public void setEmailUsuario(String emailUsuario) {
        this.emailUsuario = emailUsuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPnombre() {
        return this.pnombre;
    }
    
    public void setPnombre(String pnombre) {
        this.pnombre = pnombre;
    }
    public String getAppaterno() {
        return this.appaterno;
    }
    
    public void setAppaterno(String appaterno) {
        this.appaterno = appaterno;
    }
    public String getApmaterno() {
        return this.apmaterno;
    }
    
    public void setApmaterno(String apmaterno) {
        this.apmaterno = apmaterno;
    }
    public String getRutUsuario() {
        return this.rutUsuario;
    }
    
    public void setRutUsuario(String rutUsuario) {
        this.rutUsuario = rutUsuario;
    }
    public Date getFechanac() {
        return this.fechanac;
    }
    
    public void setFechanac(Date fechanac) {
        this.fechanac = fechanac;
    }
    public String getDireccionUsuario() {
        return this.direccionUsuario;
    }
    
    public void setDireccionUsuario(String direccionUsuario) {
        this.direccionUsuario = direccionUsuario;
    }
    public int getNumtelefono() {
        return this.numtelefono;
    }
    
    public void setNumtelefono(int numtelefono) {
        this.numtelefono = numtelefono;
    }
    public Set getMantencions() {
        return this.mantencions;
    }
    
    public void setMantencions(Set mantencions) {
        this.mantencions = mantencions;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }
    public Set getSolicitudarriendos() {
        return this.solicitudarriendos;
    }
    
    public void setSolicitudarriendos(Set solicitudarriendos) {
        this.solicitudarriendos = solicitudarriendos;
    }
    public Set getReportes() {
        return this.reportes;
    }
    
    public void setReportes(Set reportes) {
        this.reportes = reportes;
    }




}


