package Model;
// Generated 10-10-2021 15:45:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="USUARIO"
    ,schema="BDCLETA"
)
public class Usuario  implements java.io.Serializable {


     private long idUsuario;
     private Rol rol;
     private String emailUsuario;
     private String password;
     private String pnombre;
     private String appaterno;
     private String apmaterno;
     private String rutUsuario;
     private Date fechanac;
     private String direccionUsuario;
     private int numtelefono;
     private Set<Mantencion> mantencions = new HashSet<Mantencion>(0);
     private Set<Venta> ventas = new HashSet<Venta>(0);
     private Set<Solicitudarriendo> solicitudarriendos = new HashSet<Solicitudarriendo>(0);
     private Set<Solicitudmantencion> solicitudmantencions = new HashSet<Solicitudmantencion>(0);
     private Set<Reporte> reportes = new HashSet<Reporte>(0);

    public Usuario() {
    }

	
    public Usuario(long idUsuario, Rol rol, String password, String pnombre, String appaterno, String rutUsuario, Date fechanac, String direccionUsuario, int numtelefono) {
        this.idUsuario = idUsuario;
        this.rol = rol;
        this.password = password;
        this.pnombre = pnombre;
        this.appaterno = appaterno;
        this.rutUsuario = rutUsuario;
        this.fechanac = fechanac;
        this.direccionUsuario = direccionUsuario;
        this.numtelefono = numtelefono;
    }
    public Usuario(long idUsuario, Rol rol, String emailUsuario, String password, String pnombre, String appaterno, String apmaterno, String rutUsuario, Date fechanac, String direccionUsuario, int numtelefono, Set<Mantencion> mantencions, Set<Venta> ventas, Set<Solicitudarriendo> solicitudarriendos, Set<Solicitudmantencion> solicitudmantencions, Set<Reporte> reportes) {
       this.idUsuario = idUsuario;
       this.rol = rol;
       this.emailUsuario = emailUsuario;
       this.password = password;
       this.pnombre = pnombre;
       this.appaterno = appaterno;
       this.apmaterno = apmaterno;
       this.rutUsuario = rutUsuario;
       this.fechanac = fechanac;
       this.direccionUsuario = direccionUsuario;
       this.numtelefono = numtelefono;
       this.mantencions = mantencions;
       this.ventas = ventas;
       this.solicitudarriendos = solicitudarriendos;
       this.solicitudmantencions = solicitudmantencions;
       this.reportes = reportes;
    }
   
     @Id 

    
    @Column(name="ID_USUARIO", unique=true, nullable=false, precision=10, scale=0)
    public long getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(long idUsuario) {
        this.idUsuario = idUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ROL", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }

    
    @Column(name="EMAIL_USUARIO", length=25)
    public String getEmailUsuario() {
        return this.emailUsuario;
    }
    
    public void setEmailUsuario(String emailUsuario) {
        this.emailUsuario = emailUsuario;
    }

    
    @Column(name="PASSWORD", nullable=false, length=10)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="PNOMBRE", nullable=false, length=25)
    public String getPnombre() {
        return this.pnombre;
    }
    
    public void setPnombre(String pnombre) {
        this.pnombre = pnombre;
    }

    
    @Column(name="APPATERNO", nullable=false, length=25)
    public String getAppaterno() {
        return this.appaterno;
    }
    
    public void setAppaterno(String appaterno) {
        this.appaterno = appaterno;
    }

    
    @Column(name="APMATERNO", length=25)
    public String getApmaterno() {
        return this.apmaterno;
    }
    
    public void setApmaterno(String apmaterno) {
        this.apmaterno = apmaterno;
    }

    
    @Column(name="RUT_USUARIO", nullable=false, length=10)
    public String getRutUsuario() {
        return this.rutUsuario;
    }
    
    public void setRutUsuario(String rutUsuario) {
        this.rutUsuario = rutUsuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHANAC", nullable=false, length=7)
    public Date getFechanac() {
        return this.fechanac;
    }
    
    public void setFechanac(Date fechanac) {
        this.fechanac = fechanac;
    }

    
    @Column(name="DIRECCION_USUARIO", nullable=false, length=30)
    public String getDireccionUsuario() {
        return this.direccionUsuario;
    }
    
    public void setDireccionUsuario(String direccionUsuario) {
        this.direccionUsuario = direccionUsuario;
    }

    
    @Column(name="NUMTELEFONO", nullable=false, precision=9, scale=0)
    public int getNumtelefono() {
        return this.numtelefono;
    }
    
    public void setNumtelefono(int numtelefono) {
        this.numtelefono = numtelefono;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Mantencion> getMantencions() {
        return this.mantencions;
    }
    
    public void setMantencions(Set<Mantencion> mantencions) {
        this.mantencions = mantencions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Solicitudarriendo> getSolicitudarriendos() {
        return this.solicitudarriendos;
    }
    
    public void setSolicitudarriendos(Set<Solicitudarriendo> solicitudarriendos) {
        this.solicitudarriendos = solicitudarriendos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Solicitudmantencion> getSolicitudmantencions() {
        return this.solicitudmantencions;
    }
    
    public void setSolicitudmantencions(Set<Solicitudmantencion> solicitudmantencions) {
        this.solicitudmantencions = solicitudmantencions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Reporte> getReportes() {
        return this.reportes;
    }
    
    public void setReportes(Set<Reporte> reportes) {
        this.reportes = reportes;
    }




}


