package Model;
// Generated 10-10-2021 15:45:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venta generated by hbm2java
 */
@Entity
@Table(name="VENTA"
    ,schema="BDCLETA"
)
public class Venta  implements java.io.Serializable {


     private long idVenta;
     private Usuario usuario;
     private Date fechora;
     private long totalventa;
     private String estadoventa;
     private Set<Detalleventa> detalleventas = new HashSet<Detalleventa>(0);
     private Set<Seguimientoenvios> seguimientoenvioses = new HashSet<Seguimientoenvios>(0);

    public Venta() {
    }

	
    public Venta(long idVenta, Usuario usuario, Date fechora, long totalventa) {
        this.idVenta = idVenta;
        this.usuario = usuario;
        this.fechora = fechora;
        this.totalventa = totalventa;
    }
    public Venta(long idVenta, Usuario usuario, Date fechora, long totalventa, String estadoventa, Set<Detalleventa> detalleventas, Set<Seguimientoenvios> seguimientoenvioses) {
       this.idVenta = idVenta;
       this.usuario = usuario;
       this.fechora = fechora;
       this.totalventa = totalventa;
       this.estadoventa = estadoventa;
       this.detalleventas = detalleventas;
       this.seguimientoenvioses = seguimientoenvioses;
    }
   
     @Id 

    
    @Column(name="ID_VENTA", unique=true, nullable=false, precision=10, scale=0)
    public long getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(long idVenta) {
        this.idVenta = idVenta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USUARIO", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHORA", nullable=false, length=7)
    public Date getFechora() {
        return this.fechora;
    }
    
    public void setFechora(Date fechora) {
        this.fechora = fechora;
    }

    
    @Column(name="TOTALVENTA", nullable=false, precision=10, scale=0)
    public long getTotalventa() {
        return this.totalventa;
    }
    
    public void setTotalventa(long totalventa) {
        this.totalventa = totalventa;
    }

    
    @Column(name="ESTADOVENTA", length=25)
    public String getEstadoventa() {
        return this.estadoventa;
    }
    
    public void setEstadoventa(String estadoventa) {
        this.estadoventa = estadoventa;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="venta")
    public Set<Detalleventa> getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set<Detalleventa> detalleventas) {
        this.detalleventas = detalleventas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="venta")
    public Set<Seguimientoenvios> getSeguimientoenvioses() {
        return this.seguimientoenvioses;
    }
    
    public void setSeguimientoenvioses(Set<Seguimientoenvios> seguimientoenvioses) {
        this.seguimientoenvioses = seguimientoenvioses;
    }




}


