package Model;
// Generated 29-10-2021 20:24:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private long idVenta;
     private Usuario usuario;
     private Date fechora;
     private long totalventa;
     private String estadoventa;
     private Set detalleventas = new HashSet(0);
     private Set seguimientoenvioses = new HashSet(0);

    public Venta() {
    }

	
    public Venta(long idVenta, Usuario usuario, Date fechora, long totalventa) {
        this.idVenta = idVenta;
        this.usuario = usuario;
        this.fechora = fechora;
        this.totalventa = totalventa;
    }
    public Venta(long idVenta, Usuario usuario, Date fechora, long totalventa, String estadoventa, Set detalleventas, Set seguimientoenvioses) {
       this.idVenta = idVenta;
       this.usuario = usuario;
       this.fechora = fechora;
       this.totalventa = totalventa;
       this.estadoventa = estadoventa;
       this.detalleventas = detalleventas;
       this.seguimientoenvioses = seguimientoenvioses;
    }
   
    public long getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(long idVenta) {
        this.idVenta = idVenta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechora() {
        return this.fechora;
    }
    
    public void setFechora(Date fechora) {
        this.fechora = fechora;
    }
    public long getTotalventa() {
        return this.totalventa;
    }
    
    public void setTotalventa(long totalventa) {
        this.totalventa = totalventa;
    }
    public String getEstadoventa() {
        return this.estadoventa;
    }
    
    public void setEstadoventa(String estadoventa) {
        this.estadoventa = estadoventa;
    }
    public Set getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set detalleventas) {
        this.detalleventas = detalleventas;
    }
    public Set getSeguimientoenvioses() {
        return this.seguimientoenvioses;
    }
    
    public void setSeguimientoenvioses(Set seguimientoenvioses) {
        this.seguimientoenvioses = seguimientoenvioses;
    }




}


